In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

In library there are prewritten functions, classes that are useful for variouse opreation one wnats to perform on the data.
Libraries are created specific task wise visualsation libs, libs for machine learning 
They are handy becasue they contain all the codes kept at one place and very useful and easy to call them out whenver we are working  



In [ ]:
#2. What is the ^ifference between Numpy array an^ List?

Numpy arrys can only store the data of same data type, whereas list can store multiple data types 
NumPy arrays are more memory efficient compared to Python lists, especially for large datasets, because they store data in contiguous memory blocks
Python lists are slower for numerical computations compared to arrays 
NumPy arrays offer a wide range of mathematical functions and operations optimized for arrays, such as element-wise operations, linear algebra whereas list dont




In [9]:
# 3. Fin^ the shape, size an^ ^imension of the following array?

import numpy as np

A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

print(np.array(A).shape)
print(np.array(A).size)

(3, 4)
12


In [11]:
#4. Write python co^e to access the first row of the following array?

A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

np.array(A)[0]

array([1, 2, 3, 4])

In [13]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

np.array(A)[2,3]

12

In [20]:
#6.  Write co^e to extract all odd-indexed elements from the given numpy array?

A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

np.array(A)[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [23]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

np.random.rand(3, 3)

array([[0.01554278, 0.24344004, 0.20340594],
       [0.21337519, 0.54439101, 0.89086457],
       [0.13558615, 0.46173983, 0.46580407]])

In [ ]:
#8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand: generates numbers likely to be any value in the range [0, 1].

np.random.randn: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).




In [25]:
#9. Write co^e to increase the ^imension of the following array?

A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]


# Increase dimension using np.expand_dims()
A_expanded = np.expand_dims(A, axis=2)

print(A)
print(A_expanded)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [27]:
#10. How to transpose the following array in NumPy?

A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

print(np.array(A).transpose())
print(np.array(A).T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [28]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

index_wise_multiplication = A2 * B2

matrix_multiplication = np.dot(A2, B2.T)  

matrix_addition = A2 + B2

matrix_subtraction = A2 - B2

matrix_division = B2 / A2

print(index_wise_multiplication)
print(matrix_multiplication)
print(matrix_addition)
print(matrix_subtraction)
print(matrix_division)


[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12.  Which function in Numpy can be use^ to swap the byte or^er of an array?
np.ndarray.byteswap()

In [30]:
#13.  What is the significance of the np.linalg.inv function?
 #ans it calculates the inverse of a given matrix
    
  

Original array:
[1 2 3 4]

Array with swapped byte order:
[16777216 33554432 50331648 67108864]


In [31]:
#14. What ^oes the np.reshape function do, and how is it use^?

#It reshapes the array into the specified shape while keeping the same elements.

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, 3))

print(arr)
print(reshaped_arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [32]:
#15. What is broadcasting in Numpy?

#broadcasting is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations. 
#It enables us to perform element-wise operations on arrays of different shapes without explicitly reshaping or duplicating the arrays.

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr2 = np.array([2, 2, 2])

result = arr1 + arr2

print(arr1)
print(arr2)
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
